### ISSUE TITLE
create build script

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/dlx-js#18]
- [ ] generate docs
- [ ] bundle JS (using Browserify)
- [ ] transpile JS (using Babel)
- [ ] upload to DLx CDN
